In [2]:
import numpy as np

In [4]:
a = np.array([12, 34, 56, 78, 100])

In [8]:
print(a)

[ 12  34  56  78 100]


In [10]:
a

array([ 12,  34,  56,  78, 100])

In [12]:
a.ndim

1

In [14]:
a.shape

(5,)

In [16]:
a1 = np.array([12, 34, True, 33.12, "Geet"])

In [18]:
a1

array(['12', '34', 'True', '33.12', 'Geet'], dtype='<U32')

In [20]:
a2 = np.array([12, 34, 55.21, 34])

In [22]:
a2.dtype

dtype('float64')

In [24]:
a2[1]

34.0

In [26]:
type(a)

numpy.ndarray

In [28]:
# speed between list and array

In [30]:
values = 1000000

list1 = list(range(values))
arr1 = np.array(list1)

In [34]:
list1;

In [36]:
import time

In [38]:
time.time()

1744258130.3818924

In [44]:
# speed of list

start_time = time.time()
newl = [i * 2 for i in list1]
print(f"time taken by list => {time.time() - start_time}")

time taken by list => 0.027994871139526367


In [46]:
start_time = time.time()
newarr = arr1 * 2
print(f"time taken by array => {time.time() - start_time}")

time taken by array => 0.003196239471435547


In [48]:
0.027994871139526367/0.003196239471435547

8.758690138743846

In [50]:
# arange

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(5, 21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [60]:
# 2d arrays

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 3], [7, 8, 2], [6, 3, 9]])

In [64]:
arr

array([[1, 2, 3],
       [4, 5, 3],
       [7, 8, 2],
       [6, 3, 9]])

In [66]:
arr.shape

(4, 3)

In [68]:
arr.size

12

In [70]:
arr.ndim

2

In [74]:
arr.flatten()

array([1, 2, 3, 4, 5, 3, 7, 8, 2, 6, 3, 9])

In [76]:
arr

array([[1, 2, 3],
       [4, 5, 3],
       [7, 8, 2],
       [6, 3, 9]])

In [78]:
arr.reshape(3, 4)

array([[1, 2, 3, 4],
       [5, 3, 7, 8],
       [2, 6, 3, 9]])

In [80]:
arr.reshape(6, 2)

array([[1, 2],
       [3, 4],
       [5, 3],
       [7, 8],
       [2, 6],
       [3, 9]])

In [82]:
arr.reshape(3,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 3],
        [7, 8]],

       [[2, 6],
        [3, 9]]])

In [84]:
arr.reshape(3,2,2).ndim

3

In [86]:
arr.reshape(6, -1)

array([[1, 2],
       [3, 4],
       [5, 3],
       [7, 8],
       [2, 6],
       [3, 9]])

In [88]:
arr.reshape(4, 3, -1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [3]],

       [[7],
        [8],
        [2]],

       [[6],
        [3],
        [9]]])

In [92]:
arr1 = np.array([[1, 2, 3], [4, 2, 5], [6, 9, 3]])

In [94]:
arr1

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 3]])

In [96]:
np.linalg.inv(arr1)

array([[-0.56521739,  0.30434783,  0.05797101],
       [ 0.26086957, -0.2173913 ,  0.10144928],
       [ 0.34782609,  0.04347826, -0.08695652]])

In [98]:
np.linalg.det(arr1)

68.99999999999996

In [100]:
np.linalg.eig(arr1)

EigResult(eigenvalues=array([11.65562749, -1.38675741, -4.26887008]), eigenvectors=array([[ 0.32048827,  0.83297228, -0.29196665],
       [ 0.53688866, -0.3441243 , -0.47556003],
       [ 0.78040876, -0.43328472,  0.82981813]]))

In [102]:
arr2 = np.array([[1, 5, 3], [12, 1, 5], [10, 9, 3]])

In [104]:
arr1 @ arr2

array([[ 55,  34,  22],
       [ 78,  67,  37],
       [144,  66,  72]])

In [106]:
arr

array([[1, 2, 3],
       [4, 5, 3],
       [7, 8, 2],
       [6, 3, 9]])